config/routes.rb
KataWebsite::Application.routes.draw do
  get "simple_website/home", as: :home
  get "simple_website/about", as: :about
  get "simple_website/contact", as: :contact
  
  root :to => 'simple_website#home'
  

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  attr_accessible :comments, :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/simple_website_controller.rb
class SimpleWebsiteController < ApplicationController

	def home
		
	end
	def about
		
	end
	def contact
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_website_helper.rb
module SimpleWebsiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KataWebsite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/simple_website/about.html.erb
<h1>Sample App</h1>
<p>
  This is the about page for the
  <a href="http://thefonso.com/">thefonso.com</a>
  sample application.
</p>

app/views/simple_website/contact.html.erb
<h1>Contact Us</h1>
<p>
  This is the contact page for the
  <a href="http://thefonso.com/">thefonso.com</a>
  sample application.
</p>
<p>
    <!-- Now we need a form with a user model -->
    <!-- it "should have a name, email and comments field" -->
    <%= form_tag("/simple_website/formresult", :method => "get") do %>
      <div class="field">
        <%= label_tag :name %><br />
        <%= text_field_tag :name %>
      </div>
      <div class="field">
        <%= label_tag :email %><br />
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :comments %><br />
        <%= text_area_tag :comments %>
      </div>
      <div class="actions">
        <%= submit_tag %>
      </div>
    <% end %>
    <!-- it should post content to database  -->
    <!-- TODO this is visitors/new -->
</p>

app/views/simple_website/home.html.erb
<h1>Sample App</h1>

<ul>
	<li><%= link_to 'home', home_path %></li>
	<li><%= link_to 'about', about_path %></li>
	<li><%= link_to'contact', contact_path %></li>
</ul>

<p>
  This is the home page for the
  <a href="http://thefonso.com/">thefonso.com</a>
  sample application.

 <!--  TODO - create nav bar with links to other pages, make this a partial -->



</p>